on: push

name: Test

jobs:
  test_lin:
    name: Ubuntu test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Test
        run: |
          npm install
          npm test
